#!/bin/bash
#SBATCH --job-name=data_comb
#SBATCH -p sched_mit_twcronin
#SBATCH -N 1           # nodes requested
#SBATCH -n 1           # tasks requested
#SBATCH -c 1           # cpus requested
#SBATCH -o h.out     # send stdout to outfile
#SBATCH -e h.err     # send stderr to errfile
#SBATCH --time=10:00:00    # time limit

source ~/.bashrc

python Comb.py
	
# Note: submit this script as 'sbatch script.sh'
