#!/bin/bash
# Calculate heights for all lat lon values
# Does this through starting one sbatch job for each lon value
# Each sbatch job then loops through all of the lat values

for lon2 in {0..715..5}
do
	sbatch height_base_case_sbatch $lon2
done

squeue -u benr19 -i1

