#!/bin/bash
#SBATCH --job-name=height_tc
#SBATCH -p sched_mit_twcronin
#SBATCH -N 1           # nodes requested
#SBATCH -n 1           # tasks requested
#SBATCH -c 1           # cpus requested
#SBATCH -o h.out     # send stdout to outfile
#SBATCH -e h.err     # send stderr to errfile
#SBATCH --time=20:00:00    # time limit

source ~/.bashrc

for lat2 in {-180..180..5}
do
	python height_temp_case.py $lat2 $1
done

# Note: submit this script as 'sbatch script.sh'
